name: "pre-release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1